version: "3"
    
services:
  web:
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    external_links:
      - db:db
volumes:
  wordpress_data: {}

networks:
  cluster-wp:
    external:
      name: ingress_wp_network
